cabinet/urls.py
from django.contrib.auth.views import (
    PasswordResetCompleteView,
    PasswordResetDoneView,
)
from django.urls import path, reverse_lazy

from .views import (
    cabinet,
    logout_view,
    registration_view,
    ProfileView,
    login_view,
    ResetPass,
    PageView,
    ConfirmPass,
    ModuleDetailView,
    LessonDetailView,
    Notifications,
    login_view_new_password,
    has_viewed,
    change_password,
    mark_comment_as_viewed,
    create_payment,
    was_paid_for,
)

app_name = 'cabinet'

urlpatterns = [
    path('', login_view, name="home"),
    path('cabinet/', cabinet, name="cabinet"),
    path('cabinet/create-payment/', create_payment, name='create_payment'),
    path('cabinet/was-paid-for/', was_paid_for, name='was_paid_for'),
    path('cabinet/notifications/', Notifications.as_view(), name="notifications"),
    path('cabinet/notifications/has-viewed', has_viewed, name="has_viewed"),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),
    path('<slug:slug>/', PageView.as_view(), name="text_page"),
    path('cabinet/profile/<str:username>', ProfileView.as_view(), name='profile'),
    path('cabinet/profile/<str:username>/change-password/', change_password, name='change_password'),
    path('cabinet/<str:slug>', ModuleDetailView.as_view(), name="module"),
    path('cabinet/<str:module_slug>/<str:slug>', LessonDetailView.as_view(), name="lesson"),
    path('cabinet/mark_comment_as_viewed/<int:comment_id>/', mark_comment_as_viewed, name='mark_comment_as_viewed'),

    path('auth/password_reset/', ResetPass.as_view(), name='password_reset'),
    path('auth/password_reset/done/', PasswordResetDoneView.as_view(template_name='users/management/password-reset-done.html'), name='password_reset_done'),
    path('auth/reset/<uidb64>/<token>/', ConfirmPass.as_view(), name='password_reset_confirm'),
    path('auth/reset/done/', login_view_new_password, name='password_reset_complete'),
]

losdesign/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cabinet.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cabinet/forms.py
from django import forms

from .models import Notification, Comment


class HomeWorkSendForm(forms.ModelForm):
    class Meta:
        model = Notification
        fields = ('text',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'file')

cabinet/views.py
import random
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
import math

from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.html import strip_tags
from django.views import View
from django.views.generic import TemplateView, UpdateView, DetailView
import re

from .forms import HomeWorkSendForm, CommentForm
from .models import Profile, Page, Module, Lesson, Notification, Comment, Order

import uuid
from yookassa import Configuration, Payment
Configuration.account_id = settings.ACCOUNT_ID_YOOKASSA
Configuration.secret_key = settings.SECRET_KEY_YOOKASSA


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('cabinet/')

        context = {
            'message': False
        }
        
        return render(request, 'main.html', context=context)

    email = request.POST['email']
    password = request.POST['password']

    try:
        user = User.objects.get(email=email)
    except:
        return render(request, 'main.html', {'message': 'Введенный логин не найден'})

    user = authenticate(request, username=user.username, password=password)

    if user is not None:
        login(request, user)
        next_url = request.GET.get('next', 'cabinet:cabinet')
        return redirect(next_url)

    context = {
        'message': 'Введенный пароль неверный'
    }

    return render(request, 'main.html', context=context)


@login_required
def cabinet(request: HttpRequest) -> HttpResponse:
    modules = Module.objects.filter(status=True)

    total_homeworks = Lesson.objects.filter(
        has_homework=True,
        module__status=True
    ).count()

    done_homeworks = Notification.objects.filter(
        user=request.user,
        is_done=True,
        lesson__has_homework=True,
        lesson__module__status=True
    ).count()

    lessons_with_hw = Module.objects.filter(
        status=True,
        lessons__has_homework=True,
    ).exists()

    count_lessons_percent = done_homeworks / total_homeworks * 100

    lessons_done_count = {}
    lessons_with_homework = {}
    for module in modules:
        lessons_done_count[module.id] = Notification.objects.filter(
            user=request.user,
            is_done=True,
            lesson__module=module,
            lesson__has_homework=True,
            lesson__module__status=True
        ).count()
        lessons_with_homework[module.id] = Lesson.objects.filter(
            has_homework=True,
            module=module,
            module__status=True
        ).count()

    greetings = [
        'Сегодня прекрасный день, чтобы узнать что-то новое!',
        'Ну что, покорим сегодня новые вершины знаний?',
        'Долой тоску и уныние — мир дизайна ждет тебя!',
        'Сегодня ты станешь ближе к своим мечтам и целям!',
        'Смелость и упорство — ключ к успеху!'
    ]

    greeting = random.choice(greetings)

    # Получаем последний платеж пользователя
    last_order = Order.objects.filter(user=request.user).order_by('-payment_date').first()
    payment_status = last_order.payment_status if last_order else None

    context = {
        'user': request.user,
        'modules': modules,
        'lessons_done_count': lessons_done_count,
        'total_homeworks': total_homeworks,
        'done_homeworks': done_homeworks,
        'lessons_with_homework': lessons_with_homework,
        'count_lessons_percent': math.floor(count_lessons_percent),
        'greeting': greeting,
        'payment_status': payment_status,
        'lessons_with_hw': lessons_with_hw,
    }
    return render(request, 'cabinet.html', context=context)


@login_required
def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect('cabinet:home')


def registration_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('password')

        if User.objects.filter(email=email).exists():
            context = {
                'name_value': name,
                'password_value': password,
                'message': 'Пользователь с таким E-mail уже существует'
            }
            return render(request, 'registration.html', context=context)

        if len(password) < 8:
            context = {
                'name_value': name,
                'email_value': email,
                'message': 'Пароль должен быть не меньше 8-ми символов'
            }
            return render(request, 'registration.html', context=context)

        if not re.search(r'[a-zA-Z]', password) or not re.search(r'[0-9]', password):
            context = {
                'name_value': name,
                'email_value': email,
                'message': 'Пароль должен содержать буквы и цифры'
            }
            return render(request, 'registration.html', context=context)

        try:
            username = email.split('@')[0]
            user = User.objects.create_user(username=username, password=password, email=email)
            Profile.objects.create(user=user, name=name)
        except Exception as e:
            return render(request, 'registration.html', {'message': e})

        context = {
            'name': name,
            'email': email,
            'password': password,
            'protocol': request.scheme,
            'domain': request.get_host(),
        }
        html_message = render_to_string('registration_success_email.html', context)
        plain_message = strip_tags(html_message)
        send_mail(
            'Успешная регистрация',
            plain_message,
            settings.EMAIL_HOST_USER,
            [email],
            html_message=html_message,
        )

        user = authenticate(
            username=username,
            password=password
        )

        if user is not None:
            login(request, user)
            return redirect('/cabinet/')

        return render(request, 'registration.html', {'message': 'Ошибка аутентификации'})

    context = {
        'name_value': '',
        'email_value': '',
        'password_value': '',
        'message': False
    }
    return render(request, 'registration.html', context=context)


class ResetPass(PasswordResetView):
    template_name = 'users/management/password-reset.html'
    email_template_name = 'users/management/password_reset_email.html'
    html_email_template_name = 'users/management/password_reset_email.html'
    success_url = '/auth/password_reset/done/'

    def form_valid(self, form):
        email = form.cleaned_data['email']
        if not User.objects.filter(email=email).exists():
            messages.error(self.request, 'Пользователь с таким E-mail не существует')
            return render(self.request, self.template_name, {'form': form})
        return super().form_valid(form)


class ConfirmPass(PasswordResetConfirmView):
    template_name = 'users/management/password-confirm.html'
    success_url = '/cabinet/'

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        password = request.POST.get('new_password1')
        password2 = request.POST.get('new_password2')

        if password2 != password:
            messages.error(request, 'Пароли не совпадают')
            return HttpResponseRedirect(f'/auth/reset/{kwargs["uidb64"]}/{kwargs["token"]}/')

        if form.is_valid():
            if len(password) < 8:
                messages.error(request, 'Пароль должен быть не меньше 8 символов')
                return HttpResponseRedirect(f'/auth/reset/{kwargs["uidb64"]}/{kwargs["token"]}/')

            if not re.search(r'[a-zA-Z]', password) or not re.search(r'[0-9]', password):
                messages.error(request, 'Пароль должен содержать буквы и цифры')
                return HttpResponseRedirect(f'/auth/reset/{kwargs["uidb64"]}/{kwargs["token"]}/')

            return self.form_valid(form)

        return self.form_invalid(form)


def login_view_new_password(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('cabinet/')

        return render(request, 'users/management/password-reset-complete.html')

    email = request.POST['email']
    password = request.POST['password']

    try:
        user = User.objects.get(email=email)
    except:
        return render(request, 'main.html', {'message': 'Введенный логин не найден'})

    user = authenticate(request, username=user.username, password=password)

    if user is not None:
        login(request, user)
        return redirect('cabinet/')

    return render(request, 'users/management/password-reset-complete.html', {'message': 'Неверно введен логин или пароль'})


class ProfileView(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = "name", "phone", "photo", "location", "bio"
    template_name = 'profile.html'

    def get_object(self, queryset=None):
        username = self.kwargs.get('username')
        return get_object_or_404(Profile, user__username=username)

    def get_success_url(self):
        return reverse("cabinet:profile", kwargs={"username": self.object.user.username})

    def form_valid(self, form):
        try:

templates/base.html
<!DOCTYPE html>
<html lang="ru">

{% load static %}

<head>
    <title>{% block title %} Title {% endblock %}</title>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="{% static 'fav.png' %}" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="d-flex flex-column">

    {% block content %}
        Content
    {% endblock %}

    {% include 'includes/scripts.html' %}

</body>
</html>

templates/cabinet.html
{% extends 'base.html' %}

{% load custom_filters %}
{% load static %}

{% block title %}
    Личный кабинет — LosDesign
{% endblock %}

{% block content %}

    {% include 'includes/header.html' %}

    <main>
        {% if user.profile.is_active or user.is_staff %}
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="header__block">
                            <h2>Привет, {% firstof user.profile.name user.username %}!</h2>
                            {% if not request.user.is_staff %}
                                <p>{{ greeting }}</p>
                            {% endif %}
                        </div>
                        {% if request.user.is_staff %}
                            <div class="statusbar__header">
                                Предпросмотр материала
                            </div>
                        {% else %}
                            {% if lessons_with_hw %}
                                <div class="statusbar__header">
                                    Выполнено {{ done_homeworks }} из {{ total_homeworks }} заданий
                                    <div class="progress">
                                        <div
                                            class="progress-bar"
                                            role="progressbar"
                                            style="width: {{ count_lessons_percent }}%"
                                            aria-valuenow="{{ count_lessons_percent }}"
                                            aria-valuemin="0"
                                            aria-valuemax="100"
                                        ></div>
                                    </div>
                                </div>
                            {% else %}
                                <div class="mb-4"></div>
                            {% endif %}
                        {% endif %}
                    </div>
                    {% for module in modules %}
                        <div class="col-md-6 col-lg-4">
                            <div class="module">
                                <a href="{% url 'cabinet:module' slug=module.slug %}">
                                    {% if not request.user.is_staff %}
                                        {% if lessons_with_homework|get_item:module.id > 0 %}
                                            {% if lessons_done_count|get_item:module.id == lessons_with_homework|get_item:module.id %}
                                                <picture class="is_done">
                                                    <img src="{% static 'img/done.svg' %}" alt="">
                                                </picture>
                                            {% else %}
                                                <span>Выполнено {{ lessons_done_count|get_item:module.id }} из {{ lessons_with_homework|get_item:module.id }} заданий</span>
                                            {% endif %}
                                        {% endif %}
                                    {% endif %}
                                    <div class="ratio ratio-16x9">
                                        <div>
                                            <picture>
                                                {% if module.picture %}
                                                    <img src="{{ module.picture.url }}" alt="">
                                                {% else %}
                                                    <img src="{% static 'img/lorem.svg' %}" alt="">
                                                {% endif %}
                                            </picture>
                                        </div>
                                    </div>
                                    {{ module.title }}
                                </a>
                            </div>
                        </div>
                    {% empty %}
                        <p>Пока ничего нет</p>
                    {% endfor %}
                </div>
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="header__block">
                            <h2>Привет, {% firstof user.profile.name user.username %}!</h2>
                            <p>К сожалению, курс пока не доступен.</p>
                        </div>
                    </div>
                    <div class="col-12 pay__info">
                        <div>
                            <picture>
                                <img src="{% static 'img/pay.png' %}" alt="">
                            </picture>
                            <div>
                                <h4>Оплата курса</h4>
                                {% if payment_status == 'pending' %}
                                    <p>Вы уже оплатили курс.</p>
                                    <p class="pending">
                                        Оплата в обработке ...
                                        <a href="{% url 'cabinet:was_paid_for' %}">Обновить статус</a>
                                    </p>
                                {% else %}
                                    <p>Перед началом обучения, вам необходимо произвести оплату за курс в размере <b>20 000 руб.</b></p>
                                    <a href="{% url 'cabinet:create_payment' %}">Оплатить курс</a>
                                    <!--<a href="{% url 'cabinet:create_payment' %}">Оплатить курс</a>-->
                                {% endif %}
                            </div>
                        </div>
                        <div>
                            <div class="ratio ratio-16x9">
                                <div>
                                    <link rel="stylesheet" href="https://cdn.plyr.io/3.7.8/plyr.css" />
                                    <script src="https://cdn.plyr.io/3.7.8/plyr.js"></script>

                                    <video id="player" playsinline controls>
                                        <source src="{% static 'start.mp4' %}" type="video/mp4" />
                                    </video>

                                    <script>
                                        const player = new Plyr('#player', {
                                            controls: ['play-large', 'play', 'progress', 'current-time', 'mute', 'volume', 'fullscreen'],
                                            settings: [],
                                        });
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </main>

    {% include 'includes/footer.html' %}

{% endblock %}

templates/comment_notification_email.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Новое сообщение</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 100%;
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.05);
        }
        .header {
            background-color: #3EFF97;
            color: #0E0D11;
            padding: 16px;
            text-align: center;
            border-radius: 2rem;
        }
        .header svg {
            width: 50%;
            height: auto;
            margin-top: 1rem;
        }
        .content {
            padding: 20px;
        }
        .content p {
            font-size: 16px;
            line-height: 1.5;
        }
        .content a {
            color: #007BFF;
            text-decoration: none;
        }
        .footer {
            text-align: center;
            padding: 10px;
            font-size: 14px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <picture>
                <img src="{% static 'img/logo_comment_notification.svg' %}" alt="">
            </picture>
            <h1>Новое сообщение</h1>
            <h4>go.losdesign.ru</h4>
        </div>
        <div class="content">
            <p>Здравствуйте, <b>{{ name }}</b></p>
            <p>У вас новое сообщение от куратора.</p>
            <p>Перейдите на платформу, чтобы просмотреть сообщение: <a href="{{ lesson_url }}">перейти на платформу</a></p>
        </div>
        <div class="footer">
            <p>Если вы не ожидали этого письма — проигнорируйте его.</p>
        </div>
    </div>
</body>
</html>

templates/main.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Авторизация — LosDesign
{% endblock %}

{% block content %}

    <div class="form__block__1" data-aos="fade-in">
        <div>
            <picture>
                <img src="{% static 'img/logo.svg' %}" alt="">
            </picture>
            <h3>Авторизация</h3>
            {% if message %}
                <div id="message__alert">
                    <span class="alert__error">
                        {{ message }}
                    </span>
                </div>
            {% endif %}
            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}
                <input type="email" name="email" class="form-control" placeholder="E-mail" required>
                <input type="password" name="password" class="form-control" placeholder="Пароль" required>
                <a href="{% url 'cabinet:password_reset' %}">Не помню пароль</a>
                <input type="submit" class="send" value="Войти в профиль">
                <a href="{% url 'cabinet:registration' %}" class="registration">Создать профиль</a>
            </form>
        </div>
        <ul class="cpy" style="position:absolute;">
            <li><a href="{% url 'cabinet:text_page' 'oferta' %}">Оферта</a></li>
            <li><a href="{% url 'cabinet:text_page' 'kontakty' %}">Контакты</a></li>
            <li><a href="{% url 'cabinet:text_page' 'rekvizity' %}">Реквизиты</a></li>
            <li><a href="{% url 'cabinet:text_page' 'politika-konfidencialnosti' %}">Политика конфиденциальности</a></li>
        </ul>
    </div>

{% endblock %}

templates/module.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ module.title }} — LosDesign
{% endblock %}

{% block content %}

    {% include 'includes/header.html' %}

        <main>
            <div class="container lessons__page">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="aside__block">
                            <a href="{% url 'cabinet:home' %}" class="back__arrow">
                                <svg width="18" height="16" viewBox="0 0 18 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M9.02102 15.5597C9.00621 15.5746 8.55225 15.6884 8.01229 15.8125C7.47227 15.9366 7.02461 16.0192 7.01741 15.9961C7.01028 15.973 6.9544 15.5982 6.8933 15.1632C6.77057 14.2896 6.47341 13.2697 6.15588 12.6318C5.16614 10.6438 3.39036 9.32745 1.23658 8.98532L0.688129 8.89818V8.01998V7.1417L1.18523 7.0583C4.44202 6.51191 6.56529 4.07678 6.96249 0.432595C6.98841 0.194633 7.0194 0 7.03133 0C7.14117 0 8.96117 0.438616 8.99559 0.473361C9.02048 0.498487 9.00196 0.721568 8.95438 0.969012C8.42773 3.70904 6.91977 5.93867 4.96291 6.87093L4.49352 7.09457L14.1462 7.11208L17.3125 7.1232V8.90055L14.1305 8.91168L4.50058 8.92926L5.09319 9.22951C6.63056 10.0084 7.84773 11.5363 8.56452 13.587C8.76877 14.1713 9.07697 15.5033 9.02102 15.5597Z"/>
                                </svg>
                                Вернуться к модулям
                            </a>
                            <div>
                                <div class="ratio ratio-16x9">
                                    <div>
                                        <picture>
                                            {% if module.picture %}
                                                <img src="{{ module.picture.url }}" alt="">
                                            {% else %}
                                                <img src="{% static 'img/lorem.svg' %}" alt="">
                                            {% endif %}
                                        </picture>
                                    </div>
                                </div>
                                {{ module.text|safe }}
                                {% if lessons_with_hm %}
                                    {% if lessons_percent == 100 %}
                                        <span>Все задания выполнены</span>
                                    {% elif lessons_percent > 0 %}
                                        <div class="progress">
                                            <div class="progress-bar" role="progressbar" style="width: {{ lessons_percent }}%" aria-valuenow="{{ lessons_percent }}" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9 mt-5 mt-lg-0">
                        <div class="row">
                            <div class="col-12">
                                <h3>{{ module.title }}</h3>
                            </div>
                            {% for lesson in lessons %}
                                <div class="col-md-6 col-lg-4">
                                    <div class="lesson">
                                        <a href="{% url 'cabinet:lesson' module_slug=module.slug slug=lesson.slug %}">
                                            <div class="ratio ratio-16x9">
                                                <div>
                                                    <picture>
                                                        {% if lesson.picture %}
                                                            <img src="{{ lesson.picture.url }}" alt="">
                                                        {% else %}
                                                            <img src="{% static 'img/lorem.svg' %}" alt="">
                                                        {% endif %}
                                                    </picture>
                                                </div>
                                            </div>
                                            <h2>{{ lesson.title }}</h2>
                                            {% if lesson.id in lesson_done %}
                                                <picture class="is_done">
                                                    <img src="{% static 'img/done.svg' %}" alt="">
                                                </picture>
                                            {% endif %}
                                            {% if lesson.id in lesson_paused and lesson.id not in lesson_done %}
                                                <em class="in_process">В процессе ...</em>
                                            {% endif %}
                                        </a>
                                    </div>
                                </div>
                            {% empty %}
                                <div class="col-12">
                                    <p>Уроки пока не загружены ...</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </main>

    {% include 'includes/footer.html' %}

{% endblock %}

templates/registration.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Регистрация — LosDesign
{% endblock %}

{% block content %}

    <div class="form__block__1" data-aos="fade-in">
        <div>
            <picture>
                <img src="{% static 'img/logo.svg' %}" alt="">
            </picture>
            <h3>Регистрация</h3>
            {% if message %}
                <div id="message__alert">
                    <span class="alert__error">
                        {{ message }}
                    </span>
                </div>
            {% endif %}
            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}
                <input type="text" name="name" class="form-control" placeholder="Как вас зовут?" value="{{ name_value }}" required>
                <input type="email" name="email" class="form-control" placeholder="Ваша почта" value="{{ email_value }}" required>
                <input type="password" name="password" class="form-control" value="{{ password_value }}" placeholder="Придумайте пароль" required>
                <input type="submit" class="send" value="Создать профиль">
                <a href="{% url 'cabinet:home' %}" class="registration">Войти в профиль</a>
            </form>
        </div>
        <ul class="cpy">
            <li><a href="{% url 'cabinet:text_page' 'oferta' %}">Оферта</a></li>
            <li><a href="{% url 'cabinet:text_page' 'kontakty' %}">Контакты</a></li>
            <li><a href="{% url 'cabinet:text_page' 'rekvizity' %}">Реквизиты</a></li>
            <li><a href="{% url 'cabinet:text_page' 'politika-konfidencialnosti' %}">Политика конфиденциальности</a></li>
        </ul>
    </div>

{% endblock %}