cabinet/urls.py
from django.contrib.auth.views import (
    PasswordResetCompleteView,
    PasswordResetDoneView,
)
from django.urls import path, reverse_lazy

from .views import (
    cabinet,
    logout_view,
    registration_view,
    ProfileView,
    login_view,
    ResetPass,
    PageView,
    ConfirmPass,
    ModuleDetailView,
    LessonDetailView,
    Notifications,
    login_view_new_password,
    has_viewed,
    change_password,
    mark_comment_as_viewed,
    create_payment,
    was_paid_for,
)

app_name = 'cabinet'

urlpatterns = [
    path('', login_view, name="home"),
    path('cabinet/', cabinet, name="cabinet"),
    path('cabinet/create-payment/', create_payment, name='create_payment'),
    path('cabinet/was-paid-for/', was_paid_for, name='was_paid_for'),
    path('cabinet/notifications/', Notifications.as_view(), name="notifications"),
    path('cabinet/notifications/has-viewed', has_viewed, name="has_viewed"),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),
    path('<slug:slug>/', PageView.as_view(), name="text_page"),
    path('cabinet/profile/<str:username>', ProfileView.as_view(), name='profile'),
    path('cabinet/profile/<str:username>/change-password/', change_password, name='change_password'),
    path('cabinet/<str:slug>', ModuleDetailView.as_view(), name="module"),
    path('cabinet/<str:module_slug>/<str:slug>', LessonDetailView.as_view(), name="lesson"),
    path('cabinet/mark_comment_as_viewed/<int:comment_id>/', mark_comment_as_viewed, name='mark_comment_as_viewed'),

    path('auth/password_reset/', ResetPass.as_view(), name='password_reset'),
    path('auth/password_reset/done/', PasswordResetDoneView.as_view(template_name='users/management/password-reset-done.html'), name='password_reset_done'),
    path('auth/reset/<uidb64>/<token>/', ConfirmPass.as_view(), name='password_reset_confirm'),
    path('auth/reset/done/', login_view_new_password, name='password_reset_complete'),
]

losdesign/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cabinet.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/users/management/password-confirm.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  Восстановление пароля — LosDesign
{% endblock %}

{% block content %}

    <div class="form__block__1" data-aos="fade-in">
        <div>
            <picture>
                <img src="{% static 'img/logo.svg' %}" alt="">
            </picture>
            {% if validlink %}
                <h3>Новый пароль</h3>
                {% if messages %}
                    <div id="message__alert">
                        {% for message in messages %}
                            <span class="alert__{{ message.tags }}">
                                {{ message }}
                            </span>
                        {% endfor %}
                    </div>
                {% endif %}
                <form method="post" class="needs-validation" novalidate>
                    {% csrf_token %}
                    <input type="password" name="new_password1" class="form-control" placeholder="Придумайте пароль" required>
                    <input type="password" name="new_password2" class="form-control" placeholder="Повторите пароль" required>
                    <input type="submit" class="send" value="Обновить пароль">
                </form>
            {% else %}
                <h3>Ссылка для сброса пароля недействительна!</h3>
                <p class="p-5">Скорее всего она уже была использована. Пожалуйста, запросите смену пароля еще раз.</p>
                <a href="{% url 'cabinet:password_reset' %}" class="send">Запросить пароль заново</a>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/users/management/password-reset-complete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Пароль изменен — LosDesign
{% endblock %}

{% block content %}

    <div class="form__block__1" data-aos="fade-in">
        <picture>
            <img src="{% static 'img/logo.svg' %}" alt="">
        </picture>
        <h3>Пароль изменен</h3>
        <p>Вы можете авторизоваться по новому паролю</p>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            <input type="email" name="email" class="form-control" placeholder="E-mail" required>
            <input type="password" name="password" class="form-control" placeholder="Пароль" required>
            <input type="submit" class="send" value="Войти в профиль">
        </form>
        {% if messages %}
            <div id="message__alert">
                {% for message in messages %}
                    <span class="alert__{{ message.tags }}">
                        {{ message }}
                    </span>
                {% endfor %}
            </div>
        {% endif %}
    </div>

{% endblock %}

templates/users/management/password-reset-done.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Восстановление пароля — LosDesign
{% endblock %}

{% block content %}

    <div class="form__block__1" data-aos="fade-in">
        <picture>
            <img src="{% static 'img/logo.svg' %}" alt="">
        </picture>
        <h3>Восстановить пароль</h3>
        <p class="ps-3 pe-3">Письмо с инструкциями по восстановлению пароля отправлено на почту</p>
        <a href="{% url 'cabinet:home' %}" class="registration w-auto">На главную</a>
    </div>

{% endblock %}

templates/users/management/password-reset.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Восстановление пароля — LosDesign
{% endblock %}

{% block content %}

    <div class="form__block__1" data-aos="fade-in">
        <div>
            <picture>
                <img src="{% static 'img/logo.svg' %}" alt="">
            </picture>
            <h3>Восстановить пароль</h3>
            {% if messages %}
                <div id="message__alert">
                    {% for message in messages %}
                        <span class="alert__{{ message.tags }}">
                            {{ message }}
                        </span>
                    {% endfor %}
                </div>
            {% endif %}
            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}
                <input type="email" name="email" class="form-control" placeholder="Введите свой E-mail" required>
                <input type="submit" class="send" value="Сбросить пароль">
                <a href="{% url 'cabinet:home' %}" class="registration">Войти в профиль</a>
            </form>
        </div>
    </div>

{% endblock %}

templates/users/management/password_reset_email.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Сброс пароля</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 100%;
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.05);
        }
        .header {
            background-color: #0E0D11;
            color: #ffffff;
            padding: 16px;
            text-align: center;
            border-radius: 2rem;
        }
        .header svg {
            width: 50%;
            height: auto;
            margin-top: 1rem;
        }
        .content {
            padding: 20px;
        }
        .content p {
            font-size: 16px;
            line-height: 1.5;
        }
        .content a {
            color: #007BFF;
            text-decoration: none;
        }
        .footer {
            text-align: center;
            padding: 10px;
            font-size: 14px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <picture>
                <img src="{% static 'img/logo_reset_password.svg' %}" alt="">
            </picture>
            <h1>Сброс пароля</h1>
            <h4>go.losdesign.ru</h4>
        </div>
        <div class="content">
            <p>Здравствуйте! Данное письмо направлено на адрес <b>{{ email }}</b>, указанный при регистрации аккаунта на платформе <a href="https://go.losdesign.ru">LosDesign</a>.</p>
            <p>Для сброса пароля, необходимо пройти по <a href="{{ protocol }}://{{ domain }}{% url 'cabinet:password_reset_confirm' uidb64=uid token=token %}">ссылке</a>.</p>
            <p>Ваш логин для авторизации, на случай, если вы забыли: <b>{{ email }}</b></p>
        </div>
        <div class="footer">
            <p>Если вы не отправляли запрос на сброс пароля — проигнорируйте данное письмо</p>
        </div>
    </div>
</body>
</html>